Feature/add keyvault support
nventive/DotNet.Backend.Template pull request #30
Opened 2021-11-19 15:26 UTC by DamienLaffond

## Proposed Changes

 - Feature 
 
Add Keyvault support , to implement secure hosting for secure value.
Add Integration for Web & Function with Extension code.
Add Component into ARM Template

- Refactoring (no functional changes, no api changes)

Blank line

 - Build or CI related changes

no changes , parameter was already there ( pipeline.deploy 'appconfigurationsku')

## What is the current behavior?

No keyvault - No local usersecret 

## What is the new behavior?

KeyVault Parameter in AppServiceSettings is set automatically , it mean that by default Keyvault IS implemented.
With AccessPolicies for Site / Function / Slots.

If Development environment , use of the secrets.json .

## Checklist

Please check if your PR fulfills the following requirements:

- [ ] Documentation has been added/updated
- [ ] Automated Unit / Integration tests for the changes have been added/updated
- [ ] Contains **NO** breaking changes
- [ ] Updated the Changelog
- [ ] Associated with an issue

## Other information
You still have too add yourself into keyvault policies to manage secret with your nventive account.

2021-11-19 19:21 UTC, DamienLaffond commented
Bug with Usersecrets.json

2021-11-19 19:33 UTC, DamienLaffond commented
Cycle reference in arm - wip

2021-11-19 19:39 UTC, DamienLaffond commented
Cycle referene in arm - wip  (Function slot)

2021-11-22 18:50 UTC, baptiste-nv approved these changes

2021-12-14 14:18 UTC, baptiste-nv commented on src/Content/Backend/NV.Templates.Backend.sln
> -//#if (Azure)
Why did you remove template tags? It will break up the dotnet new command and will include unwanted projects in generated code

2021-12-14 14:20 UTC, baptiste-nv requested changes
You should re-enable the template tags before completing the PR

2021-12-14 14:43 UTC, DamienLaffond commented on src/Content/Backend/NV.Templates.Backend.sln
> -//#if (Azure)
Fixed

2021-12-14 15:45 UTC, baptiste-nv approved these changes

2021-12-14 15:48 UTC, merged